# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantのバージョンをひとまず1.9.0としておく
Vagrant.require_version "= 1.9.0"

VAGRANTFILE_API_VERSION = 2
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # https://docs.vagrantup.com
  # すべてのマシンで同じ鍵を使う
  config.ssh.insert_key = false
  config.vm.synced_folder ".", "/vagrant"
  # ボックスのアップデートチェック
  config.vm.box_check_update = false

  config.vm.box = "https://github.com/tommy-muehle/puppet-vagrant-boxes/releases/download/1.1.0/centos-7.0-x86_64.box"
end
